apiVersion: v1
kind: Pod
metadata:
  name: sec-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        # Define the environment variable
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            secretKeyRef:
              name: mysecret   # name of the secret file 
              key: username  # specify the key -> and it's value will be fetched 
        - name: secound
          valueFrom:
            secretKeyRef:
              name: mysecret   # name of the secret file 
              key: password  # specify the key -> and it's value will be fetched
  restartPolicy: Never